In [2]:
a=1

In [3]:
isinstance(a,int)

True

In [4]:
a="Hello"

In [5]:
isinstance(a,int)   

False

In [6]:
a=="Hello"

True

In [8]:
# This is a comment
"This is a comment"

'This is a comment'

In [11]:
a=1
isinstance(a,int)

True

In [13]:
isinstance(a,float)

False

In [14]:
a=1.0
isinstance(a,float)

True

In [15]:
1,000,000

(1, 0, 0)

In [16]:
1_000_000

1000000

In [20]:
"{:,}".format(1_000_000)

'1,000,000'

In [21]:
'Florida'

'Florida'

In [22]:
'Florida\'s Turnpike'

"Florida's Turnpike"

In [23]:
"Florida's Turnpike"

"Florida's Turnpike"

In [24]:
"Florida's \tTurnpike"

"Florida's \tTurnpike"

In [25]:
'Florida\'s \tTurnpike'

"Florida's \tTurnpike"

In [32]:
print('Florida\'s \tTurnpike')

Florida's 	Turnpike


In [33]:
print('Florida\'s \nTurnpike')

Florida's 
Turnpike


In [34]:
print('Florida\'s \\Turnpike')

Florida's \Turnpike


In [36]:
print(r'Floridas Turnpike')

Floridas Turnpike


In [37]:
print('''
usage: florida-man [option]
    -h             Display this usage message
    -t degrees     Set temperature in F
    -a             Include alligatros
    ''')


usage: florida-man [option]
    -h             Display this usage message
    -t degrees     Set temperature in F
    -a             Include alligatros
    


In [38]:
"Flo" "rida"

'Florida'

In [40]:
s1="Cape "
s2="Canaveral"
s1+s2

'Cape Canaveral'

In [41]:
cities = ["Miami", "Orlando", "Tampa", "Jacksonville"]
cities[0]

'Miami'

In [42]:
cities[1:3]

['Orlando', 'Tampa']

In [43]:
cities[0:4]

['Miami', 'Orlando', 'Tampa', 'Jacksonville']

In [44]:
cities.append("Tallahassee")

In [45]:
cities.append(123)

In [46]:
cities

['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Tallahassee', 123]

In [48]:
cities.pop()

123

In [49]:
cities

['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Tallahassee']

In [51]:
cities.pop()

'Tallahassee'

In [52]:
cities

['Miami', 'Orlando', 'Tampa', 'Jacksonville']

In [53]:
cities[2]="Tampa-St. Petersburg"

In [54]:
cities

['Miami', 'Orlando', 'Tampa-St. Petersburg', 'Jacksonville']

In [57]:
cities[0]="Orlando"

In [58]:
cities

['Orlando', 'Orlando', 'Tampa-St. Petersburg', 'Jacksonville']

In [96]:
counties=("Miami-Dade", "Orange", "Hillsborough", "Duval") # Tuple, not a list

In [97]:
counties[0]="Miami"

TypeError: 'tuple' object does not support item assignment

In [98]:
# Dictionaries
jurisdictions={"Miami":"Dade County", "Orlando":"Orange County"}

In [99]:
jurisdictions["Jacksonville"]="Duval"

In [100]:
print(jurisdictions)

{'Miami': 'Dade County', 'Orlando': 'Orange County', 'Jacksonville': 'Duval'}


In [101]:
print(jurisdictions['Miami'][0])

D


In [102]:
print(jurisdictions['Miami'][5])

C


In [103]:
print(jurisdictions['Miami'][0:6])

Dade C


In [104]:
jurisdictions["Miami"]="abc"

In [105]:
print(jurisdictions)

{'Miami': 'abc', 'Orlando': 'Orange County', 'Jacksonville': 'Duval'}


In [106]:
national_parks={"Everglades","Biscayne","Dry Tortugas"}  # Set
print(national_parks)

{'Biscayne', 'Everglades', 'Dry Tortugas'}


In [107]:
a=1;b=2

In [109]:
x="Miami Beaach"

if x in cities:
    print("found",x,"city")
elif x in counties:
    print("found", x, "county")
else:
    print(r"didn't find",x)


didn't find Miami Beaach


In [110]:
for x in cities:
    print(x,"city")

Miami city
Orlando city
Tampa-St. Petersburg city
Jacksonville city


In [111]:
x=1
while x<5:
    print(x)
    x+=1

1
2
3
4


In [119]:
x=1
while x>-5:
    print(x)
    x +=-1

1
0
-1
-2
-3
-4


In [120]:
x=1
while x<5:
    print(x)
    x += 1
    if x>3:
        break

1
2
3


In [122]:
import os
import numpy as np
from transportation_tutorials import data as td

ModuleNotFoundError: No module named 'transportation_tutorials'

In [123]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [1]:
def greeting():
    print("Hello, Florida!")

In [2]:
greeting()

Hello, Florida!


In [3]:
def to_kilo(mi, ft):
    dist = mi + ft/5280
    return 1.60934 * dist

In [5]:
to_kilo(26, 1155)

42.194883125

In [11]:
def to_kilo2(mi, ft=0):
    dist = mi + ft/5280
    return 1.60934 * dist
to_kilo2(10)

16.0934

In [10]:
to_kilo2(10,10)

16.096447992424242

In [16]:
def to_kilo3(mi, ft=0, y=0):
    dist = mi + ft/5280 + y/1760
    return 1.60934 * dist

In [17]:
to_kilo3(26, y=38)

41.877587113636366

In [18]:
to_kilo3(26, ft=1, y=38)

41.87789191287879

In [19]:
to_kilo3(ft=1, y=38)

TypeError: to_kilo3() missing 1 required positional argument: 'mi'

In [22]:
def county_names(*names):
    for name in names:
        print(name, "county")

In [23]:
county_names("p", "l", "m")

p county
l county
m county


In [24]:
def highway(*names, heading=None):
    if heading:
        print(heading)
    for name in names:
        print("-",name)

In [25]:
highway("A A", "M C", heading="Unofficial Names")

Unofficial Names
- A A
- M C


In [26]:
highway("A A", "M C")

- A A
- M C


In [27]:
def highway2(*names, heading="Unofficial Names"):
    if heading:
        print(heading)
    for name in names:
        print("-",name)

In [28]:
highway2("A A", "M C")

Unofficial Names
- A A
- M C


In [29]:
highway2("A A", "M C", heading="Unofficial Names2")

Unofficial Names2
- A A
- M C


In [31]:
def highway3(**names):
    for key, value in names.items():
        print(key,"is",value)

highway3(I_75="Alligator Alley", US_1="Magic Carpet")


I_75 is Alligator Alley
US_1 is Magic Carpet


In [41]:
A={"I_75":"Alligator Alley", "US_1":"Magic Carpet"}
print(A['I_75'])

Alligator Alley


In [44]:
A.keys()

dict_keys(['I_75', 'US_1'])

In [46]:
A.values()

dict_values(['Alligator Alley', 'Magic Carpet'])

In [47]:
lambda km: km / 1.60934

<function __main__.<lambda>(km)>

In [49]:
list(map(lambda km: km / 1.60934, [5, 10, 42]))

[3.106863683249034, 6.213727366498068, 26.097654939291886]

In [50]:
list(lambda km: km / 1.60934, [5, 10, 42])

TypeError: list expected at most 1 argument, got 2

In [51]:
for i in 1 to 5:
    print(i)

SyntaxError: invalid syntax (3683155868.py, line 1)

In [54]:
for i in (1:5):
    print(i)

SyntaxError: invalid syntax (1474168111.py, line 1)

In [ ]:
speeds = {
    'rural highway': 70,
    'urban highway': 55,
    'residential': 30,
}

for i in speed_limits:
    print(speed_limits[i])

In [75]:
x = list(range(5000))
y = 0

In [76]:
for i in x:
    y = y + i**2
y

41654167500

In [77]:
y=0

for i in x:
    y = y + i

y

12497500

In [78]:
import numpy as np
z = np.arange(5)
(z**2).sum()
z

array([0, 1, 2, 3, 4])

In [84]:
%%timeit
x = list(range(5))
y = 0
for i in x:
    y = y + i**2


240 ns ± 1.96 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [85]:
print(x)

[0, 1, 2, 3, 4]


In [88]:
a = np.asarray([11,22,33,44])
a

array([11, 22, 33, 44])

In [89]:
a = np.array([11,22,33,44])
a

array([11, 22, 33, 44])

In [92]:
a = np.arange(11,44)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [93]:
a = np.arange(11,44,11)
a

array([11, 22, 33])

In [98]:
a = np.array([11, 44])
a

array([11, 44])